resolver: lts-17.5
system-ghc: false
packages:
- ./git-align
- ./git-align-vis

ghc-options:
  $everything: -haddock -j 
  $locals: -fhpc

stack-colors: error=31:good=32:shell=35:dir=34:recommendation=32:target=95:module=35:package-component=95:secondary=92:highlight=32
